name: pamplemousse's blog
title: pamplemousse's blog
description: Some thoughts and writings related to projects I work on.
theme: jekyll-theme-cayman
repository: pamplemousse/blog
markdown: kramdown
plugins:
    - jekyll-sitemap
